---
- name: Playbook to configure execution environments
  hosts: builder
  gather_facts: false
  connection: local
  vars_files:
    - vault.yml
  tasks:

#    - name: Debug all variables
#      debug:
#        var: hostvars[inventory_hostname]
#
#    - debug:
#        var: ee_list

    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder

    - name: Add Execution Environment
      ansible.builtin.include_role:
        name: infra.controller_configuration.execution_environments
...