---
ee_list:
  - name: "config_as_code"
#    de_or_ee: ee
    pull: always
    dependencies:
      galaxy:
        collections:
          - name: infra.controller_configuration
            version: 2.5.1
          - name: infra.ah_configuration
            version: 2.0.3
          - name: infra.ee_utilities
            version: 3.1.2
          - name: awx.awx
            version: 23.1.0
          - name: containers.podman
            version: 1.10.3
          - name: community.general
            version: 7.3.0

  - name: "dynatrace_eda_ee"
#    de_or_ee: ee
    pull: always
    dependencies:
      galaxy:
        collections:
          - name: dynatrace.oneagent
          - name: dynatrace.oneagent_deploy

#  - name: "dynatrace_eda_de"
#    de_or_ee: de
#    pull: always
#    dependencies:
#      galaxy:
#        collections:
#          - name: dynatrace.even_driven_ansible
#          - name: servicenow.itsm

ee_base_image: "{{ ah_host }}/ee-minimal-rhel8:latest"
ee_image_push: true
ee_prune_images: false
ee_create_ansible_config: false
ee_pull_collections_from_hub: false
ee_create_controller_def: true
...
